import Head from 'next/head'

export default function Layout({ children }) {

  return (
    <>
      <Head>
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Display-Heavy.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Display-Black.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Display-BlackItalic.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Display-Bold.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Display-BoldItalic.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Display-HeavyItalic.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Display-Light.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Display-LightItalic.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Display-Medium.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Display-MediumItalic.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Display-Regular.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Display-RegularItalic.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Display-Semibold.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Display-SemiboldItalic.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Display-Thin.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Display-ThinItalic.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Display-Ultralight.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Display-UltralightItalic.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Italic.ttf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Rounded-Black.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Rounded-Bold.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Rounded-Heavy.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Rounded-Light.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Rounded-Medium.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Rounded-Regular.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Rounded-Semibold.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Rounded-Thin.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Rounded-Ultralight.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Text-Black.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Text-BlackItalic.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Text-Bold.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Text-BoldItalic.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Text-Heavy.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Text-HeavyItalic.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Text-Light.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Text-LightItalic.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Text-Medium.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Text-MediumItalic.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Text-Regular.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Text-RegularItalic.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Text-Semibold.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Text-SemiboldItalic.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Text-Thin.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Text-ThinItalic.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Text-Ultralight.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro-Text-UltralightItalic.otf"
        />
        <link
          as="font"
          rel="preload"
          crossOrigin=""
          href="/fonts/sf-pro-display/SF-Pro.ttf"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
        />
        <script src="./slide-stories.js"></script>
      </Head>

      {children}

      <style jsx global>{`
        body {
          font-family: sans-serif;
          background-color: #eaf1f6;
          overflow: auto !important;
        }
      `}</style>
    </>
  )
}
